name: Markdown link checker

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
        with:
          use-quiet-mode: 'yes'
          folder-path: 'engine, examples/apps, examples/projects, network, test, tool_services, .github'
          file-path: './README.md, ./LICENSE'
          config-file: '.github/workflows/mlc_config.json'
