name: Upload platformio library

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    description: 'manual upload'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: publish
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
      run: |

        # ***** Luos engine publication *****
        pio package pack
        pio package publish --owner luos --non-interactive


        # ***** Gate publcation *****
        cd tool_services/gate
        mkdir Examples

        # Arduino
        mkdir Examples/Arduino
        mkdir Examples/Arduino/Serial
        cp -r ../../examples/projects/Arduino/gate_serialcom/* Examples/Arduino/Serial/

        # l0
        mkdir Examples/l0
        mkdir Examples/l0/Serial
        cp -r ../../examples/projects/l0/gate_serialcom/* Examples/l0/Serial/

        # NUCLEO-F072RB
        mkdir Examples/NUCLEO-F072RB
        mkdir Examples/NUCLEO-F072RB/Serial
        cp -r ../../examples/projects/NUCLEO-F072RB/gate_serialcom/* Examples/NUCLEO-F072RB/Serial/

        # NUCLEO-F401RE
        mkdir Examples/NUCLEO-F401RE
        mkdir Examples/NUCLEO-F401RE/Serial
        cp -r ../../examples/projects/NUCLEO-F401RE/gate_serialcom/* Examples/NUCLEO-F401RE/Serial/

        # NUCLEO-F410RB
        mkdir Examples/NUCLEO-F410RB
        mkdir Examples/NUCLEO-F410RB/Serial
        cp -r ../../examples/projects/NUCLEO-F410RB/gate_serialcom/* Examples/NUCLEO-F410RB/Serial/

        # NUCLEO-G431KB
        mkdir Examples/NUCLEO-G431KB
        mkdir Examples/NUCLEO-G431KB/Serial
        cp -r ../../examples/projects/NUCLEO-G431KB/gate_serialcom/* Examples/NUCLEO-G431KB/Serial/

        # NUCLEO-G474RE
        mkdir Examples/NUCLEO-G474RE
        mkdir Examples/NUCLEO-G474RE/Serial
        cp -r ../../examples/projects/NUCLEO-G474RE/gate_serialcom/* Examples/NUCLEO-G474RE/Serial/

        # NUCLEO-L432KC
        mkdir Examples/NUCLEO-L432KC
        mkdir Examples/NUCLEO-L432KC/Serial
        cp -r ../../examples/projects/NUCLEO-L432KC/gate_serialcom/* Examples/NUCLEO-L432KC/Serial/

        # STM32F4-discovery
        mkdir Examples/STM32F4-discovery
        mkdir Examples/STM32F4-discovery/Serial
        cp -r ../../examples/projects/STM32F4-discovery/gate_serialcom/* Examples/STM32F4-discovery/Serial/

        pio package pack
        pio package publish --owner luos --non-interactive
        cd ../..


        # ***** Inspector publication *****
        cd tool_services/inspector
        mkdir Examples

        # Arduino
        mkdir Examples/Arduino
        mkdir Examples/Arduino/Serial
        cp -r ../../examples/projects/Arduino/inspector_serialcom/* Examples/Arduino/Serial/

        # l0
        mkdir Examples/l0
        mkdir Examples/l0/Serial
        cp -r ../../examples/projects/l0/inspector_serialcom/* Examples/l0/Serial/

        # NUCLEO-F072RB
        mkdir Examples/NUCLEO-F072RB
        mkdir Examples/NUCLEO-F072RB/Serial
        cp -r ../../examples/projects/NUCLEO-F072RB/inspector_serialcom/* Examples/NUCLEO-F072RB/Serial/

        # NUCLEO-F401RE
        mkdir Examples/NUCLEO-F401RE
        mkdir Examples/NUCLEO-F401RE/Serial
        cp -r ../../examples/projects/NUCLEO-F401RE/inspector_serialcom/* Examples/NUCLEO-F401RE/Serial/

        # NUCLEO-F410RB
        mkdir Examples/NUCLEO-F410RB
        mkdir Examples/NUCLEO-F410RB/Serial
        cp -r ../../examples/projects/NUCLEO-F410RB/inspector_serialcom/* Examples/NUCLEO-F410RB/Serial/

        # NUCLEO-G431KB
        mkdir Examples/NUCLEO-G431KB
        mkdir Examples/NUCLEO-G431KB/Serial
        cp -r ../../examples/projects/NUCLEO-G431KB/inspector_serialcom/* Examples/NUCLEO-G431KB/Serial/

        # NUCLEO-G474RE
        mkdir Examples/NUCLEO-G474RE
        mkdir Examples/NUCLEO-G474RE/Serial
        cp -r ../../examples/projects/NUCLEO-G474RE/inspector_serialcom/* Examples/NUCLEO-G474RE/Serial/

        # NUCLEO-L432KC
        mkdir Examples/NUCLEO-L432KC
        mkdir Examples/NUCLEO-L432KC/Serial
        cp -r ../../examples/projects/NUCLEO-L432KC/inspector_serialcom/* Examples/NUCLEO-L432KC/Serial/

        # STM32F4-discovery
        mkdir Examples/STM32F4-discovery
        mkdir Examples/STM32F4-discovery/Serial
        cp -r ../../examples/projects/STM32F4-discovery/inspector_serialcom/* Examples/STM32F4-discovery/Serial/

        pio package pack
        pio package publish --owner luos --non-interactive
        cd ../..