name: Upload platformio library

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  check_valid_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: No upload if tag is a release candidate
        if: contains(github.event.ref, 'rc')
        run: |
          echo "Stop job: do not upload a release candidate tag"
          exit 1

  deploy_engine:
    needs: check_valid_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: publish luos engine
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
        run: |
          # ***** Luos engine publication *****
          pio package pack
          pio package publish --owner luos --non-interactive

  deploy_gate:
    needs: check_valid_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: publish gate tool
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
        run: |
          # ***** Gate publication *****
          cd tool_services/gate
          mkdir examples

          # Arduino
          mkdir examples/Arduino
          mkdir examples/Arduino/serial
          cp -r ../../examples/projects/Arduino/gate_serialcom/* examples/Arduino/serial/

          # l0
          mkdir examples/l0
          mkdir examples/l0/serial
          cp -r ../../examples/projects/l0/gate_serialcom/* examples/l0/serial/

          # NUCLEO-F072RB
          mkdir examples/NUCLEO-F072RB
          mkdir examples/NUCLEO-F072RB/serial
          cp -r ../../examples/projects/NUCLEO-F072RB/gate_serialcom/* examples/NUCLEO-F072RB/serial/

          # NUCLEO-F401RE
          mkdir examples/NUCLEO-F401RE
          mkdir examples/NUCLEO-F401RE/serial
          cp -r ../../examples/projects/NUCLEO-F401RE/gate_serialcom/* examples/NUCLEO-F401RE/serial/

          # NUCLEO-F410RB
          mkdir examples/NUCLEO-F410RB
          mkdir examples/NUCLEO-F410RB/serial
          cp -r ../../examples/projects/NUCLEO-F410RB/gate_serialcom/* examples/NUCLEO-F410RB/serial/

          # NUCLEO-G431KB
          mkdir examples/NUCLEO-G431KB
          mkdir examples/NUCLEO-G431KB/serial
          cp -r ../../examples/projects/NUCLEO-G431KB/gate_serialcom/* examples/NUCLEO-G431KB/serial/

          # NUCLEO-G474RE
          mkdir examples/NUCLEO-G474RE
          mkdir examples/NUCLEO-G474RE/serial
          cp -r ../../examples/projects/NUCLEO-G474RE/gate_serialcom/* examples/NUCLEO-G474RE/serial/

          # NUCLEO-L432KC
          mkdir examples/NUCLEO-L432KC
          mkdir examples/NUCLEO-L432KC/serial
          cp -r ../../examples/projects/NUCLEO-L432KC/gate_serialcom/* examples/NUCLEO-L432KC/serial/

          # STM32F4-discovery
          mkdir examples/STM32F4-discovery
          mkdir examples/STM32F4-discovery/serial
          cp -r ../../examples/projects/STM32F4-discovery/gate_serialcom/* examples/STM32F4-discovery/serial/

          pio package pack
          pio package publish --owner luos --non-interactive
          cd ../..

  deploy_inspector:
    needs: check_valid_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: publish inspector tool
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
        run: |
          # ***** Inspector publication *****
          cd tool_services/inspector
          mkdir examples

          # Arduino
          mkdir examples/Arduino
          mkdir examples/Arduino/serial
          cp -r ../../examples/projects/Arduino/inspector_serialcom/* examples/Arduino/serial/

          # l0
          mkdir examples/l0
          mkdir examples/l0/serial
          cp -r ../../examples/projects/l0/inspector_serialcom/* examples/l0/serial/

          # NUCLEO-F072RB
          mkdir examples/NUCLEO-F072RB
          mkdir examples/NUCLEO-F072RB/serial
          cp -r ../../examples/projects/NUCLEO-F072RB/inspector_serialcom/* examples/NUCLEO-F072RB/serial/

          # NUCLEO-F401RE
          mkdir examples/NUCLEO-F401RE
          mkdir examples/NUCLEO-F401RE/serial
          cp -r ../../examples/projects/NUCLEO-F401RE/inspector_serialcom/* examples/NUCLEO-F401RE/serial/

          # NUCLEO-F410RB
          mkdir examples/NUCLEO-F410RB
          mkdir examples/NUCLEO-F410RB/serial
          cp -r ../../examples/projects/NUCLEO-F410RB/inspector_serialcom/* examples/NUCLEO-F410RB/serial/

          # NUCLEO-G431KB
          mkdir examples/NUCLEO-G431KB
          mkdir examples/NUCLEO-G431KB/serial
          cp -r ../../examples/projects/NUCLEO-G431KB/inspector_serialcom/* examples/NUCLEO-G431KB/serial/

          # NUCLEO-G474RE
          mkdir examples/NUCLEO-G474RE
          mkdir examples/NUCLEO-G474RE/serial
          cp -r ../../examples/projects/NUCLEO-G474RE/inspector_serialcom/* examples/NUCLEO-G474RE/serial/

          # NUCLEO-L432KC
          mkdir examples/NUCLEO-L432KC
          mkdir examples/NUCLEO-L432KC/serial
          cp -r ../../examples/projects/NUCLEO-L432KC/inspector_serialcom/* examples/NUCLEO-L432KC/serial/

          # STM32F4-discovery
          mkdir examples/STM32F4-discovery
          mkdir examples/STM32F4-discovery/serial
          cp -r ../../examples/projects/STM32F4-discovery/inspector_serialcom/* examples/STM32F4-discovery/serial/

          pio package pack
          pio package publish --owner luos --non-interactive
          cd ../..

  deploy_pipe:
    needs: check_valid_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: publish pipe driver
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
        run: |
          # ***** Pipe publication *****
          cd tool_services/pipe
          # We don't publish examples with this one.

          pio package pack
          pio package publish --owner luos --non-interactive
          cd ../..

  deploy_robus:
    needs: check_valid_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: publish robus network
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PIO_TOKEN }}
        run: |
          # ***** Robus network publication *****
          cd network/robus_network
          # We don't publish examples with this one.

          pio package pack
          pio package publish --owner luos --non-interactive
          cd ../..
